### ISSUE TITLE
Address and Name Validation

### ISSUE THREAD

**Issue by Philipify** [SagePayments/PaymentsJS#35]
I am currently using this in a development environment and it does not appear to be validating the address and/or name of the user attached to the card when we process the payment? I see only validation methods for the Expirtaion Date, Card Number and CVV is that all that is being validated or is it different for varying cards?

**Comment by thlinux1107** [comment]
Philip,
I received your request to our API Support team (sdksupport@paya.com) and have replied to that message. I'm copying my response here in case it helps anyone else.

What form of validation are you requesting? We submit AVS data to the payment processor and receive back validation on the AVS data submitted. Within PaymentsJS you'll find the field "avsResult" which will be blank if no AVS data was provided. Otherwise the field will have the following values:
Y: Address and 5-digit Zip Code match
Z: 5-digit Zip Code matches only
A: Address matches only
N: Neither Address nor Zip Code match
X: Address and 9-digit Zip Code match
W: 9-digit Zip Code matches only
U: Address info not verified for domestic transaction. Returned if the US bank does not support non-US AVS or if the AVS in a US bank is not functioning properly
R: Retry - System unavailable
S: Service not supported
E: Address verification not allowed for card type
Are you receiving any data in this field? If you are submitting the billing elements and not receiving anything back it could indicate an issue in how the data is being passed.

**Comment by thlinux1107** [comment]
Also:
One item I missed that you mentioned was the "name". I'm assuming that you mean the cardholder name. This item is not validated within a bankcard payment processing environment other than to pass it when it is included. The name is not a requirement for authorization.
